### DISCUSSION TITLE
Helix setup?

### DISCUSSION THREAD

**Discussion by TornaxO7** [pr2502/ra-multiplex#78] [Q&A] [answered]
Did anyone succeed to set this up for helix? If yes, could you please share your config?

**Comment by pr2502** [comment, marked as answer]
I'm using it with helix myself, does the example config not work?

Edit: Oh, it looks like the example config for helix is way outdated. I'll have to fix that, sorry.

My `~/.config/helix/languages.toml` has this bit in it:
```toml
[language-server.rust-analyzer]
args = ["client", "--server-path", "rust-analyzer"]
command = "/nix/store/sfl5jyc488kfmczpa5x68xvp4rq7sgin-ra-multiplex-0.2.4-git/bin/ra-multiplex"
```

My `~/.config/ra-multiplex/config.toml` has these lines in it:
```toml
connect = "/home/user/.cache/ra-mux/ra-mux.sock"
listen = "/home/user/.cache/ra-mux/ra-mux.sock"
pass_environment = ["PATH"]
```

And I have a user service `systemctl --user cat ra-mux` like this:
```conf
# /home/user/.config/systemd/user/ra-mux.service
[Install]
WantedBy=default.target

[Service]
ExecStart=/nix/store/sfl5jyc488kfmczpa5x68xvp4rq7sgin-ra-multiplex-0.2.4-git/bin/ra-multiplex server
ExecStartPre=/nix/store/vb8mdklw65p9wikp97ybmnyay0xzipx3-coreutils-9.5/bin/install -d -m0700 /home/user/.cache/ra-mux
Type=simple

[Unit]
Description=Rust analyzer multiplex server
```

Entering any shell environment that has `rust-analyzer` in PATH (like `ra-multiplex`s own repo) works as expected.

This is on nixos with no rust-analyzer or rustc installed globally, only per-project shells. You can make it easier with a more traditional distro. Without the PATH passing, pointing the service to the single rust-analyzer with an absolute path.
